<?php

/**
 * Implement hooks
 */

function briefcase_menu() {
    $menu['briefcase'] = array(
        'title' => 'Briefcase',
        'description' => 'View briefcase items',
        'access callback' => true,
        'page callback' => 'briefcase_page',
    );
    return $menu;
}

function briefcase_block_info() {
    $blocks['briefcase'] = array(
        'info' => t('Briefcase block')
    );
    $blocks['briefcase link'] = array(
        'info' => t('Briefcase link')
    );
    return $blocks;
}

function briefcase_block_configure($delta = '') {
    $form = array();
    return $form;
}

function briefcase_block_view($delta = '') {
    $block = array();

    dpm($delta);
    $block['subject'] = null;
    $block['content'] = 'hello world';

    return $block;
}

/**
 * Page callbacks
 */
function briefcase_page() {
		$page = array();
		$page['container_prefix'] = array(
			'#prefix' => "<div id='dsa'>",
		);
		$page['form'] = drupal_get_form('briefcase_download_form');
		$page['container_suffix'] = array(
			'#suffix' => "</div>",
		);
		return $page;
}

function briefcase_download_form() {
	$form['pdf_'] = array(
		'#type' => 'checkbox',
		'#title' => t('PDF or property title'),
	);
	$form['submit'] = array(
		'#type'	=> 'submit',
		'#value' => t('Save'),
	);
	return $form;
}

function briefcase_download_form_submit( $form_id, $form_values ) {
	drupal_set_message( t( $messsage ) );
}